#%RAML 1.0
# TODO organize raml documentation
title: Reincarnate API
version: v0.0.1
protocols: [ HTTPS ]
baseUri: https://api.immanuelqrw.com
mediaType: application/json
securitySchemes:
  oauth_2_0: !include oauth_2_0.raml
# TODO move endpoints to separate files
uses:
  words: !include words.raml
  languages: !include languages.raml
  wordTypes: !include wordTypes.raml
  randomizer: !include randomizer.raml
# TODO Create member resourceType
# TODO Create rate-limited resource type
resourceTypes:
  collection: !include resourceTypes/collection.raml
  member: !include resourceTypes/member.raml
traits:
  secured: !include traits/secured.raml
  rateLimited: !include traits/rate-limited.raml
securedBy: [ oauth_2_0 ]
types: # TODO place in other files?
  BaseEntity:
    type: object
    properties:
      createdOn?: datetime
      modifiedOn?: datetime
      removedOn?: datetime
  ContentEntity:
    type: BaseEntity
    properties:
      content?: file
  Language: # TODO Consider enum for name?
    type: BaseEntity
    properties:
      id: number
      name: string
  WordType: # TODO Consider enum for name?
    type: BaseEntity
    properties:
      id: number
      name: string
  Word: # TODO consider if string or object
    type: BaseEntity
    properties:
      id: number
      name: string
      wordType: WordType
      language: Language
      meaning: string
  Languages:
    type: Language[]
    minItems: 0
    uniqueItems: true
  WordTypes:
    type: WordType[]
    minItems: 0
    uniqueItems: true
  Words:
    type: Word[]
    minItems: 0
    uniqueItems: true
/words:
  description: TODO
  type: collection
  is: [ secured, rateLimited ]
  get:
    queryParameters:
      startingLetter:
        description: The starting letter of the words to search (case insensitive)
        required: false
        minLength: 1
        maxLength: 1
        type: string
        example: G
      language:
        description: The language of the words to search (case insensitive)
        required: false
        minLength: 1
        maxLength: 20
        type: string
        example: ENGLISH
      count:
        description: The amount of words to search
        required: false
        minLength: 1
        maxLength: 20
        type: number
        example: 14
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "words": [
                  {
                    "id": 13,
                    "name": "Megalomania",
                    "wordType": "NOUN",
                    "language": "ENGLISH",
                    "meaning": "Obsession with the exercise of power, especially in the domination of others."
                  },
                  {
                    "id": 994",
                    "name": "Idyllic",
                    "wordType": "ADJECTIVE",
                    "language": "ENGLISH",
                    "meaning": "(Especially of a time or place) like an idyll; extremely happy, peaceful, or picturesque."
                  },
                  {
                    "id": 54,
                    "name": "Night",
                    "wordType": "NOUN",
                    "language": "ENGLISH",
                    "meaning": "The period of darkness in each twenty-four hours; the time from sunset to sunrise."
                  }
                ]
              }
  post:
    body:
      application/json:
        example: |
          {
            "name": "Megalomania",
            "wordType": "NOUN",
            "language": "ENGLISH",
            "meaning": "Obsession with the exercise of power, especially in the domination of others."
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "words": [
                  {
                    "id": 13,
                    "name": "Megalomania",
                    "wordType": "NOUN",
                    "language": "ENGLISH",
                    "meaning": "Obsession with the exercise of power, especially in the domination of others."
                  }
                ]
              }
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "words": [
                    {
                      "id": 54,
                      "name": "Night",
                      "wordType": "NOUN",
                      "language": "ENGLISH",
                      "meaning": "The period of darkness in each twenty-four hours; the time from sunset to sunrise."
                    }
                  ]
                }
    put:
      body:
        application/json:
          example: |
            {
              "name": "Megalomania",
              "wordType": "NOUN",
              "language": "ENGLISH",
              "meaning": "Obsession with power"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "words": [
                    {
                      "id": 13,
                      "name": "Megalomania",
                      "wordType": "NOUN",
                      "language": "ENGLISH",
                      "meaning": "Obsession with power"
                    }
                  ]
                }
    patch:
      body:
        application/json:
          example: |
            {
              "meaning": "Obsession with power"
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "words": [
                    {
                      "id": 13,
                      "name": "Megalomania",
                      "wordType": "NOUN",
                      "language": "ENGLISH",
                      "meaning": "Obsession with power"
                    }
                  ]
                }
    delete:
/languages:
  description: TODO
  type: collection
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "languages": [
                  {
                    "id": 4,
                    "language": "SPANISH"
                  },
                  {
                    "id": 2,
                    "language": "FRENCH"
                  }
                ]
              }
  post:
    body:
      application/json:
        example: |
          {
            "language": "SPANISH"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "languages": [
                  {
                    "id": 4,
                    "language": "SPANISH"
                  }
                ]
              }
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "languages": [
                    {
                      "id": 4,
                      "language": "SPANISH"
                    }
                  ]
                }
    delete:
/wordTypes:
  description: TODO
  type: collection
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "wordType": [
                  {
                    "id": 6,
                    "wordType": "VERB"
                  },
                  {
                    "id": 9,
                    "wordType": "EXCLAMATION"
                  }
                ]
              }
  post:
    body:
      application/json:
        example: |
          {
            "wordType": "VERB"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "wordTypes": [
                  {
                    "id": 6,
                    "wordType": "VERB"
                  }
                ]
              }
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "wordTypes": [
                    {
                      "id": 6,
                      "wordType": "VERB"
                    }
                  ]
                }
    delete:
/randomizer:
  description: TODO
  type: collection
  is: [ secured, rateLimited ]
  get:
      language:
        description: The language of the words to search (case insensitive)
        required: false
        minLength: 1
        maxLength: 20
        type: string
        example: ENGLISH
      count:
        description: The amount of output randomized combowords to search
        required: false
        minLength: 1
        maxLength: 3
        type: number
        example: 1
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "comboword": [
                  "FallingRedRunningTiger",
                  "ExtremelyInfallibleCoordinatedIncephalopod",
                  "ForgetfulMailman"
                ]
              }