branches:
  - name: heads/develop

issues:
  - description: Database level scaffolding
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create SQL structure scripts
  - description: Loading configuration data into initial state of database
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create seed data files
  - description: For database instantiation
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create initialization scripts
  - description: API documentation
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Add Swagger Annotations
  - description: Setup for writing issues
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Create CHANGELOG
  - description: 'Basic setup for use

      * database-connection.yaml

      '
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Create configuration template filling script
  - description: 'Basic instructions for setting up application

      Includes connections to wiki (if applicable)

      '
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Create README
  - description: Record of who has contributed to this project
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - LIB
    - SCRIPT
    title: Create MANIFEST
  - description: Instructions on how to work on project
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - LIB
    - SCRIPT
    title: Create CONTRIBUTING
  - description: Diagrams for flow of project application
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create UMLs
  - description: Diagrams for flow and connections of data tables
    labels:
    - name: "[type] enhancement"
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create Database UML
  - description: 'Logging steps taken for future debugging

      Configure for each expected environment

      '
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Set up logging and Create configuration file for it
  - description: Connect build to CI/CD processes
    labels:
    - name: "[type] deployment"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Create CI/CD connection
  - description: Pre-hook analysis on code before commit
    labels:
    - name: "[type] enhancement"
    - name: "[type] deployment"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    - APP
    - LIB
    - SCRIPT
    - SITE
    title: Integrate static code analysis
  - description: Allows testing for 3rd party applications
    labels:
    - name: "[type] enhancement"
    - name: "[type] maintenance"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create test configuration endpoints
  - description: Filters are needed to pinpoint specific data
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Add filter to GET endpoints
  - description: null
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create entities
  - description: null
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create methods to access database
  - description: Allowing concurrent access
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - API
    title: Create async methods to access database
  - description: null
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Alpha
    repositoryTypes:
    - APP
    title: Set up app connection to App store
  - description: null
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - APP
    title: Set up API connection configuration
  - description: Needed for prototyping design
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - APP
    title: Develop wireframe
  - description: Needed to ensure accuracy and consistency
    labels:
    - name: "[type] enhancement"
    - name: "[type] deployment"
    - name: "[type] maintenance"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - LIB
    title: Set up Code Coverage tool with set minimum percent
  - description: Modify documentation to show intended code coverage
    labels:
    - name: "[type] documentation"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - LIB
    title: Integrate Code Coverage into documentation
  - description: Front-End design for Script
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Alpha
    repositoryTypes:
    - SCRIPT
    title: Find UI template
  - description: Modifications to make consistent with other scripts
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Alpha
    repositoryTypes:
    - SCRIPT
    title: Configure template
  - description: Website hosting
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - SITE
    title: Find hosting
  - description: Needed for security
    labels:
    - name: "[type] enhancement"
    milestone:
      description: null
      name: Pre-Alpha
    repositoryTypes:
    - SITE
    title: Set up SSL

labels:
  - name: "[type] bug"
    color: "e11d21"
    description: "Something isn't working"
  - name: "[type] breaking"
    color: "990000"
  - name: "[type] maintenance"
    color: "fbca04"
  - name: "[type] enhancement"
    color: "009800"
  - name: "[type] question"
    color: "cc317c"
  - name: "[type] discussion"
    color: "cc317c"
  - name: "[type] documentation"
    color: "207de5"
  - name: "[type] design"
    color: "eb6420"
  - name: "[type] deployment"
    color: "eb6420"
  - name: "[type] security"
    color: "9909de"
  - name: "[priority] low"
    color: "009800"
  - name: "[priority] medium"
    color: "fbca04"
  - name: "[priority] high"
    color: "eb6420"
  - name: "[priority] critical"
    color: "e11d21"
  - name: "[status] good first issue"
    color: "bfe5bf"
  - name: "[status] help wanted"
    color: "bfe5bf"
  - name: "[status] won't fix"
    color: "cccccc"
  - name: "[status] duplicate"
    color: "cccccc"
  - name: "[status] blocked"
    color: "330000"
  - name: "[status] abandoned"
    color: "000000"
  - name: "[status] in progress"
    color: "cccccc"
  - name: "[status] on hold"
    color: "e99695"
  - name: "[status] proposal"
    color: "d4c5f9"
  - name: "[status] review needed"
    color: "fbca04"
  - name: "[effort] 1"
    color: "00cc44"
  - name: "[effort] 2"
    color: "00cc99"
  - name: "[effort] 3"
    color: "00ffcc"
  - name: "[effort] 5"
    color: "999900"
  - name: "[effort] 8"
    color: "ffff00"
  - name: "[effort] 13"
    color: "883300"
  - name: "[work] chaotic"
    color: "999cd8"
    description: "Needs heavy design work"
  - name: "[work] complex"
    color: "7410d8"
    description: "Needs moderate design work"
  - name: "[work] complicated"
    color: "740260"
    description: "Needs slight design work"
  - name: "[work] obvious"
    color: "08f15f"
    description: "Needs no design work"

milestones:
  - description: Working on basic functionality
    name: Pre-Alpha
  - description: Finishing Minimum Viable Product
    name: Alpha
  - description: Bug Fixing
    name: Beta
  - description: Peer Review
    name: Release Candidate
  - description: Minimum Viable Product
    name: Initial Release

projects:
  - description: null
    title: Microservices
  - description: null
    title: Services
  - description: null
    title: REST API
  - description: null
    title: API Wrapper
  - description: External Authentication for REST-APIs
    title: OAuth2 Integration
  - description: Setup database for use in application
    title: Database Configuration
  - description: Configuration of deployment processes for quick iteration
    title: Deployment
  - description: null
    title: Performance Testing
  - description: null
    title: Stress Testing
  - description: null
    title: Regression Testing
  - description: null
    title: End to End Testing
  - description: Build structure for all data models
    title: Data Models
  - description: Coordinate access to database
    title: Data Access Layer
  - description: View layer
    title: UI
  - description: Main functionality
    title: Logic

users:
  -

variables:
  - Pre-Alpha
  - Alpha
  - Beta
  - Release Candidate
  - Initial Release
  - gpl-3.0
  - mit
  - API
  - APP
  - LIB
  - SCRIPT
  - SITE
