branches:
- name: heads/develop
issues:
- assignee:
    name: immanuelqrw
  description: Database level scaffolding
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create SQL structure scripts
- assignee:
    name: immanuelqrw
  description: Loading configuration data into initial state of database
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create seed data files
- assignee:
    name: immanuelqrw
  description: For database instantiation
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create initialization scripts
- assignee:
    name: immanuelqrw
  description: API documentation
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create RAML files for REST endpoint documentation
- assignee:
    name: immanuelqrw
  description: Setup for writing issues
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create CHANGELOG
- assignee:
    name: immanuelqrw
  description: 'Basic setup for use

    * database-connection.yaml

    '
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Create configuration template filling script
- assignee:
    name: immanuelqrw
  description: 'Basic instructions for setting up application

    Includes connections to wiki (if applicable)

    '
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create README
- assignee:
    name: immanuelqrw
  description: Record of who has contributed to this project
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create MANIFEST
- assignee:
    name: immanuelqrw
  description: Instructions on how to work on project
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create CONTRIBUTING
- assignee:
    name: immanuelqrw
  description: Claim ownership to project if there is no license specified
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create COPYRIGHT
- assignee:
    name: immanuelqrw
  description: Diagrams for flow of project application
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create UMLs
- assignee:
    name: immanuelqrw
  description: Diagrams for flow and connections of data tables
  labels:
  - name: enhancement
  - name: documentation
  milestone:
    description: null
    name: Pre-Alpha
  title: Create Database UML
- assignee:
    name: immanuelqrw
  description: 'Logging steps taken for future debugging

    Configure for each expected environment

    '
  labels:
  - name: enhancement
  milestone:
    description: null
    name: Pre-Alpha
  title: Set up logging and Create configuration file for it
labels:
- color: 9400D3
  description: Scaffolding, Unit, Integration, Regression, etc.
  name: testing
- color: FF4500
  description: Internal and External Comments and Documents
  name: documentation
- color: 8B0000
  description: Configuration and Scripting
  name: deployment
milestones:
- description: Working on basic functionality
  name: Pre-Alpha
- description: Finishing Minimum Viable Product
  name: Alpha
- description: Bug Fixing
  name: Beta
- description: Peer Review
  name: Release Candidate
- description: Minimum Viable Product
  name: Initial Release
projects:
- description: null
  title: Microservices
- description: null
  title: Services
- description: null
  title: REST API
- description: null
  title: API Wrapper
- description: External Authentication for REST-APIs
  title: OAuth2 Integration
- description: Setup database for use in application
  title: Database Configuration
- description: Configuration of deployment processes for quick iteration
  title: Deployment
- description: null
  title: Performance Testing
- description: null
  title: Stress Testing
- description: null
  title: Regression Testing
- description: null
  title: End to End Testing
- description: Build structure for all data models
  title: Data Models
- description: Coordinate access to database
  title: Data Access Layer
users:
- name: immanuelqrw
variables:
- enhancement
- testing
- documentation
- deployment
- Pre-Alpha
- Alpha
- Beta
- Release Candidate
- Initial Release
- gpl-3.0
- mit
- immanuelqrw
